// <auto-generated />
using System;
using API_Prueba.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIPrueba.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20221225002623_One")]
    partial class One
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Prueba.Model.Album", b =>
                {
                    b.Property<int>("IdAlbum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlbum"));

                    b.Property<int?>("ArtistaIdArtista")
                        .HasColumnType("int");

                    b.Property<string>("Año")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdArtista")
                        .HasColumnType("int");

                    b.Property<string>("NombreAlbum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAlbum");

                    b.HasIndex("ArtistaIdArtista");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("API_Prueba.Model.Artista", b =>
                {
                    b.Property<int>("IdArtista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdArtista"));

                    b.Property<string>("GeneroMusical")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreArtista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdArtista");

                    b.ToTable("Artistas");
                });

            modelBuilder.Entity("API_Prueba.Model.Album", b =>
                {
                    b.HasOne("API_Prueba.Model.Artista", "Artista")
                        .WithMany()
                        .HasForeignKey("ArtistaIdArtista");

                    b.Navigation("Artista");
                });
#pragma warning restore 612, 618
        }
    }
}
